GeoClient/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.views.generic import RedirectView

from main.views import ContactsIndexView, CostumersIndexView, MappingView




urlpatterns = [
    path('admin/', admin.site.urls),
    path('contacts', ContactsIndexView, name='contacts-index'),
    path('map', MappingView, name='map'),
    path('costumers', CostumersIndexView, name='costumers-index'),
    re_path(r'^.*$', RedirectView.as_view(url='map', permanent=False), name='home'),

]

agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView ,AgentDetailView , AgentUpdateView , AgentDeleteView,TaskView,TaskCreateView


app_name = 'agents'

urlpatterns = [
    path('',AgentListView.as_view(), name='agent-list'),
    path('<int:pk>/',AgentDetailView.as_view(),name='agent-detail'),
    path('view-task/',TaskView.as_view(),name='task-view'),
    path('<int:pk>/assign-task',TaskCreateView.as_view(),name='agent-tasks'),
    path('<int:pk>/update/',AgentUpdateView.as_view(),name='agent-update'),
    path('<int:pk>/delete/',AgentDeleteView.as_view(),name='agent-delete'),
    path('create/',AgentCreateView.as_view(), name='agent-create')
    

]

djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from leads.views import landing_page
from django.contrib import admin
from django.urls import path , include
from leads.views import landing_page , LandingPageView , DashboardView
from django.contrib.auth.views import LoginView , LogoutView , PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from main.views import ContactsIndexView, CostumersIndexView, MappingView
from django.urls import path, re_path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/',DashboardView.as_view(),name='dashboard'),
    path('',LandingPageView.as_view(), name = 'landing-page'),
    path('leads/', include('leads.urls',namespace="leads")),
    path('agents/', include('agents.urls',namespace="agents")),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(),name='logout'),
    path('reset_password/',PasswordResetView.as_view(),name= 'reset-password'),
    path('password-reset-done/',PasswordResetDoneView.as_view(),name= 'password_reset_done'),
    path('password-reset-complete/',PasswordResetDoneView.as_view(),name= 'password_reset_complete'),
    path('password-reset-confirm/<uidb64>/<token>/',PasswordResetConfirmView.as_view(),name= 'password_reset_confirm'),
    path('contacts', ContactsIndexView, name='contacts-index'),
    path('map', MappingView, name='map'),
    path('costumers', CostumersIndexView, name='costumers-index'),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from agents.views import TaskView
from .views import ( 
    LeadListView , LeadDetailView , LeadCreateView , LeadUpdateView , LeadDeleteView ,AssignAgentView,
    CategoryListView , CategoryDetailView, LeadCategoryUpdateView,UnassignedleadsView
)


app_name = "leads"
urlpatterns = [
    path('',LeadListView.as_view(), name='lead-list'),
    path('leads/unassinged/',UnassignedleadsView.as_view(), name='unassigend-leads'),
    path('<int:pk>/',LeadDetailView.as_view(),name='lead-detail'),
    path('<int:pk>/update/',LeadUpdateView.as_view(),name='lead-update'),
    path('<int:pk>/delete/',LeadDeleteView.as_view(),name='lead-delete'),
    path('<int:pk>/assign-agent/',AssignAgentView.as_view(),name='assign-agent'),
    path('<int:pk>/category/',LeadCategoryUpdateView.as_view(),name='lead-category-update'),
    path('create/',LeadCreateView.as_view(),name='lead-create'),
    path('categories/',CategoryListView.as_view(),name='category-list'),
    path('categories/<int:pk>/',CategoryDetailView.as_view(),name='category-detail')
]

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.forms import fields
from leads.models import Agent, UserProfile
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()

class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name',

        )

agents/views.py
from django.http import request
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from leads.models import Agent,Task
from django.shortcuts import reverse
from .forms import AgentModelForm
from .mixin import OrganisorAndLoginRequiredMixin

class AgentListView(OrganisorAndLoginRequiredMixin,generic.ListView):
    template_name = "agents/agent_list.html"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)



class AgentCreateView(OrganisorAndLoginRequiredMixin,generic.CreateView):
    template_name = "agents/agent_create.html" 
    form_class  = AgentModelForm 

    def get_success_url(self):
        return reverse("agents:agent-list")

    def form_valid(self, form ):
        agent = form.save(commit=False)
        agent.organisation = self.request.user.userprofile 
        agent.save()
        return super(AgentCreateView, self).form_valid(form)


class AgentDetailView(OrganisorAndLoginRequiredMixin , generic.DetailView):
    template_name = "agents/agent_detail.html"
    context_object_name = "agent"

    def get_queryset(self):
        return Agent.objects.all()

class AgentUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    template_name="agents/agent_update.html"
    form_class =AgentModelForm

    def get_success_url(self):
        return reverse("agents:agent-list")

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)

class AgentDeleteView(OrganisorAndLoginRequiredMixin,generic.DeleteView):
    template_name = "agents/agent_delete.html"


    def get_queryset(self):
        organisation = self.request.user.userprofile
        request_user_organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)



class TaskView(LoginRequiredMixin,generic.ListView):
    template_name="agents/tasks.html"
    context_object_name = "task"
    def get_queryset(self):
       user = self.request.user        
       if user.is_organisor:
            queryset = Task.objects.filter(task_name__isnull= False)
            queryset1= Task.objects.filter(task_descrption__isnull= False)
       else:
            queryset= Task.objects.filter(agent=user.agent).filter(done=False)
            return queryset
  
    # def get_context_data(self,**kwargs):
    #     context = super(TaskView , self).get_context_data(**kwargs)
    #     user = self.request.user

    #     context.update({
    #      "task_name":queryset,
    #      'task_desc':queryset1
    #     })


    
    #     return context
 


class TaskCreateView(OrganisorAndLoginRequiredMixin,generic.CreateView):
        template_name="create_task.html"
        context_object_name="create_task"
        def form_valid(self, form):
            form.save(commit=False)
            Task.save()
            return super(TaskCreateView, self).form_valid(form)

agents/templates/agents/agent_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}


{% block content %}
<div class="max-w-lg mx-auto">
<div class="py-5 border-b border-gray-200">
    <a class="hover:text-blue-500" href="{% url 'agents:agent-list' %}"> Go back to Agents  </a>
</div>
    <hr />
    <h1 class="text-4xl text-gray-800">Create a new Agent </h1>
    <form method="post">
    {% csrf_token %} 
     {{ form|crispy }}
     <button type="submit" class ="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
    </form>
</div>
{% endblock content %}

agents/templates/agents/agent_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}


{% block content %}

<div class="max-w-lg mx-auto">
    <div class="py-5 border-b border-gray-200">
        <a class="hover:text-blue-500" href="{% url 'agents:agent-list' %}"> Go back to agents</a>
    </div>
    <h1 class="text-3xl text-grey-200">Are you sure want to delete this agent.</h1>
    <form method="POST" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class ="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit </button>
    </form>
</div>

{% endblock content %}

agents/templates/agents/agent_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{agent.user.username}} </h1>
            <div class="flex mb-4">
            <a href="#" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                Overview
            </a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                Reviews
            </a>
            <a href="{% url 'agents:agent-update' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                Update Details
            </a>
            </div>
          <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Age </span>
            <span class="ml-auto text-gray-900">{{lead.age}}</span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Location</span>
            <span class="ml-auto text-gray-900">Alexandria </span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">Cell phone</span>
            <span class="ml-auto text-gray-900">01005090914</span>
          </div>
          <div class="flex">
            <span class="title-font font-medium text-2xl text-gray-900">$58.00</span>
            <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
            <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
              <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
              </svg>
            </button>
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>

    <a href="{% url 'leads:lead-list' %}"> Go back to leads</a>

    </body>

{% endblock content %}

agents/templates/agents/agent_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-grey-200">
            <div>
            <h1 class="text-4xl text-grey-800">Agents</h1>
            </div>
        
        <div>
            <a href="{% url 'agents:agent-create' %}">Create a new Agent</a>
        </div>
    </div>
        <hr />
      <div class="flex flex-wrap -m-4">
        {% for agent in object_list %}
        <div class="p-4 lg:w-1/2 md:w-full">
          <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
            <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
              </svg>
            </div>
            <div class="flex-grow">
              <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                {{ agent.user.username }}
              </h2>
              <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
              <a href="{% url 'agents:agent-detail' agent.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">View this Agent
                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                  <path d="M5 12h14M12 5l7 7-7 7"></path>
                </svg>
              </a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section> 

  


    {% endblock content %}

agents/templates/agents/agent_update.html
{% extends "base.html" %}
{% load tailwind_filters %}



{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.username }}</h1>
          <div class="flex mb-4">
            <a href="{% url 'agents:agent-detail' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                Overview
            </a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                Reviews
            </a>
            <a href="{% url 'agents:agent-update' agent.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                Update Details
            </a>
          </div>
          <form method="POST" action=".">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit"  class ="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit </button>
            </form>

          <div class="mt-5 py-5 border-t border-gray-200">
            <a href="{% url 'agents:agent-delete' agent.pk %}" class="w- 1/2 mt-3 text-white bg-blue-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                Delete
            </a>
          </div>
        </div>
        <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
      </div>
    </div>
  </section>

    <a href="{% url 'agents:agent-list' %}"> Go back to leads</a>

    </body>


    {% endblock content %}

agents/templates/agents/tasks.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>Geo Agency</title>
      <!-- Required meta tags -->
      <!-- semantic UI -->
      <link rel="stylesheet" type='text/css' href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.14/semantic.min.css">
      <!--Chart js-->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
      <!-- jQuery -->
      <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

  <!-- Custom fonts for this template-->
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %} " rel="stylesheet">

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'dashboard' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-address-card"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Geo-Agency</div>
      </a>
      <!-- Divider -->
      <hr class="sidebar-divider">

      <p class="text-center text-white font-weight-bold">Welcome {{request.user.username}}!</p>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'dashboard' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">
      
      <!-- Nav Item - Companies -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'leads:lead-list' %}">
          <i class="fas fa-fw fa-users"></i>
          <span>Leads</span></a>
      </li>

      <!-- Nav Item - Contact -->
      {% if request.user.is_organisor %}
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="fas fa-fw fa-user-circle"></i>
          <span>Agents</span></a>
      </li>
      {% endif %}
      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Profile -->
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="fas fa-fw fa-map-marker"></i>
          <span>Maps</span></a>
      </li>

      <!-- Nav Item - Logout -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">
          <i class="fas fa-fw fa-sign-out-alt"></i>
          <span>Logout</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">
  
    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
        <div id="content">
            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

              <!-- Sidebar Toggle (Topbar) -->
              <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                  <i class="fa fa-bars"></i>
              </button>



              <!-- Topbar Navbar -->
              <ul class="navbar-nav ml-auto">

                
                  <div class="topbar-divider d-none d-sm-block">
                    
                  </div>
                  <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" id="userDropdown" role="button"
                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span class="mr-2 dd-none d-lg-inline text-gray-600 small">{{request.user.first_name}} {{request.user.last_name}}</span>
                  <img class="img-profile rounded-circle"
                      src="{% static 'img/undraw_profile.svg' %} ">
              </a>
          </li>

                  

              </ul>

          </nav>
          <!-- End of Topbar -->

    <div class="col-sm-10 tasks">
        <div class="task-list">
            <div class="container-fluid">
            <div class="card shadow mb-4">
            <div class="card-header py-3">
            <h6 class="h3 mb-0 text-gray-800">Tasks</h6>
        </div>
        
        <div class="card-body">
           
            <div class="table-responsive-lg">
                {% for task in object_list %}     
                <div>        
                    <div class="card-header py-2 font-weight-bold bg-dark text-light">  {{ task.task_name }}
                    </div>
                    <br> 
                    <div class=container>{{ task.task_descrption }}</div>   
                    <hr>
            {% endfor %}    


        </div>		
    </div>
    </div>
    </div>
    </div>
    </div>
    </div>




    
</body>